export const RoutNames={
    MainScreen:'MainScreen',
    LoginScreen:'LoginScreen',
    SignUpScreen:'SignUp',
    ForgetPassword:'ForgetScreen',
    OtpScreen:'OtpScreen',
    NewPasswordScreen:'NewPassword',
    HomeScreen:'HomeScreen',
    AboutScreen:'AboutScreen',
    PrivacyScreen:'PrivacyScreen',
    SettingScreen:'SettingScreen',
    AnnouncementScreen:"AnnouncementScreen",
    EnrollmentScreen:"EnrollmentScreen",
    EnrolAgreement:'EnrolAgreement',
    StatusScreen:'StatusScreen',
    RenewEnrollStatus:"RenewEnrollStatus",
    DonationStatusScreen:'DonationStatusScreen',
    FamilyStatusScreen:"FamilyStatusScreen",
    UploadDonationScreen:"UploadDonationScreen",
    AnounceDetailScreen:"AnnounceDetailScreen",
    EnrollmentHistory:'EnrollmentHistory',
    FormHistoryDetailScreen:'FormHistoryDetailScreen',
    DonationHistoryDetailScreen:"DonationHistoryDetailScreen"
    
}